name: pages

on:
  push:
    branches: [ master ]
    paths:
      - "obsidian/**"
      - "quartz.config.ts"
      - "Makefile"
      - ".github/workflows/pages.yml"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: "22" }

      - name: build docs
        run: make docs

      - name: publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true