name: build-docs

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write  # needed to push the docs commit

concurrency:
  group: build-docs
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we’re going to commit back

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: build docs via make
        run: make docs

      # commit only if docs changed
      - name: commit docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): rebuild site"
          file_pattern: docs/**
          branch: main
